// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/chart.tsx";
import * as $2 from "./routes/counter.tsx";
import * as $3 from "./routes/hello/[name].tsx";
import * as $4 from "./routes/hello/index.tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Charts.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Menu.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/chart.tsx": $1,
    "./routes/counter.tsx": $2,
    "./routes/hello/[name].tsx": $3,
    "./routes/hello/index.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Charts.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Menu.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
