// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/chart.tsx";
import * as $2 from "./routes/counter.tsx";
import * as $3 from "./routes/draganddrop.tsx";
import * as $4 from "./routes/hello/[name].tsx";
import * as $5 from "./routes/hello/index.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/lifecycle.tsx";
import * as $8 from "./routes/swiper.tsx";
import * as $9 from "./routes/todo.tsx";
import * as $$0 from "./islands/Charts.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/DragAndDrop.tsx";
import * as $$3 from "./islands/LifeCycle.tsx";
import * as $$4 from "./islands/Menu.tsx";
import * as $$5 from "./islands/Swiper.tsx";
import * as $$6 from "./islands/Swiper_.tsx";
import * as $$7 from "./islands/ToDo.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/chart.tsx": $1,
    "./routes/counter.tsx": $2,
    "./routes/draganddrop.tsx": $3,
    "./routes/hello/[name].tsx": $4,
    "./routes/hello/index.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/lifecycle.tsx": $7,
    "./routes/swiper.tsx": $8,
    "./routes/todo.tsx": $9,
  },
  islands: {
    "./islands/Charts.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/DragAndDrop.tsx": $$2,
    "./islands/LifeCycle.tsx": $$3,
    "./islands/Menu.tsx": $$4,
    "./islands/Swiper.tsx": $$5,
    "./islands/Swiper_.tsx": $$6,
    "./islands/ToDo.tsx": $$7,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
